extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  quotes:
    - error
    - double
  semi:
    - error
    - always
  comma-dangle:
    - error
    - only-multiline
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": error
  no-useless-constructor: off
  space-before-function-paren:
    - error
    - never
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-unsafe-return": off
  "@typescript-eslint/no-empty-function": off
  no-multiple-empty-lines:
    - error
    - max: 1
