env:
  browser: true
  es2021: true
extends:
  - standard
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  quotes: ["error", "double"]
  semi: ["error", "always"]
  comma-dangle: ["error", "only-multiline"]
