env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  quotes:
    - error
    - double
  semi:
    - error
    - always
  comma-dangle:
    - error
    - only-multiline
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": error
  no-useless-constructor: off
  space-before-function-paren:
    - error
    - never
ignorePatterns: 
  - "**/*.spec.ts"
