version: "3.9"
services:
  socket-server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: image-local
    ports:
      - "4000:80"
    volumes:
      - ./:/server
    env_file: ./.env
