version: "3.9"
services:
  socket-server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: image-dev
    ports:
      - "4000:80"
    volumes:
      - ../:/server
    environment:
      - NODE_ENV=development
      - CONFIG_PATH=configs/env-local.yml
