version: "3.9"
services:
  socket-server:
    build:
      context: ..
      args:
        SERVER_PORT: 80
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      CONFIG_PATH: configs/env-prod.yml
